--  http://en.wikipedia.org/w/index.php?title=Maritime_identification_digits&oldid=182631834
/*
CREATE TABLE define_ais_dac (
       id serial primary key,
       country text,
       code integer
);
*/


INSERT INTO define_ais_dac (country,code) VALUES ('Adelie Land (French Southern Territories)',501);
INSERT INTO define_ais_dac (country,code) VALUES ('Afghanistan',401);
INSERT INTO define_ais_dac (country,code) VALUES ('Alaska (State of)',303);
INSERT INTO define_ais_dac (country,code) VALUES ('Albania (Republic Of)',201);
INSERT INTO define_ais_dac (country,code) VALUES ('Algeria (People''s Democratic Republic of)',605);
INSERT INTO define_ais_dac (country,code) VALUES ('American Samoa',559);
INSERT INTO define_ais_dac (country,code) VALUES ('Andorra (Principality of)',202);
INSERT INTO define_ais_dac (country,code) VALUES ('Angola (Republic of)',603);
INSERT INTO define_ais_dac (country,code) VALUES ('Anguilla',301);
INSERT INTO define_ais_dac (country,code) VALUES ('Antigua and Barbuda',304);
INSERT INTO define_ais_dac (country,code) VALUES ('Argentine Republic',701);
INSERT INTO define_ais_dac (country,code) VALUES ('Aruba',307);
INSERT INTO define_ais_dac (country,code) VALUES ('Ascension Island',608);
INSERT INTO define_ais_dac (country,code) VALUES ('Australia',503);
INSERT INTO define_ais_dac (country,code) VALUES ('Austria',203);
INSERT INTO define_ais_dac (country,code) VALUES ('Azerbaijani Republic',423);
INSERT INTO define_ais_dac (country,code) VALUES ('Azores (Portuguese isles of)',204);
INSERT INTO define_ais_dac (country,code) VALUES ('Bahamas (Commonwealth of the)',308);
INSERT INTO define_ais_dac (country,code) VALUES ('Bahamas (Commonwealth of the)',309);
INSERT INTO define_ais_dac (country,code) VALUES ('Bahamas (Commonwealth of the)',311);
INSERT INTO define_ais_dac (country,code) VALUES ('Bahrain (Kingdom of)',408);
INSERT INTO define_ais_dac (country,code) VALUES ('Bangladesh (People''s Republic of)',405);
INSERT INTO define_ais_dac (country,code) VALUES ('Barbados',314);
INSERT INTO define_ais_dac (country,code) VALUES ('Belarus (Republic of)',206);
INSERT INTO define_ais_dac (country,code) VALUES ('Belgium',205);
INSERT INTO define_ais_dac (country,code) VALUES ('Belize',312);
INSERT INTO define_ais_dac (country,code) VALUES ('Benin (Republic of)',610);
INSERT INTO define_ais_dac (country,code) VALUES ('Bermuda',310);
INSERT INTO define_ais_dac (country,code) VALUES ('Bhutan (Kingdom of)',410);
INSERT INTO define_ais_dac (country,code) VALUES ('Bolivia (Republic of)',720);
INSERT INTO define_ais_dac (country,code) VALUES ('Botswana (Republic of)',611);
INSERT INTO define_ais_dac (country,code) VALUES ('Brazil (Federative Republic of)',710);
INSERT INTO define_ais_dac (country,code) VALUES ('British Virgin Islands',378);
INSERT INTO define_ais_dac (country,code) VALUES ('Brunei Darussalam',508);
INSERT INTO define_ais_dac (country,code) VALUES ('Bulgaria (Republic of)',207);
INSERT INTO define_ais_dac (country,code) VALUES ('Burkina Faso',633);
INSERT INTO define_ais_dac (country,code) VALUES ('Burundi (Republic of)',609);
INSERT INTO define_ais_dac (country,code) VALUES ('Cambodia (Kingdom of)',514);
INSERT INTO define_ais_dac (country,code) VALUES ('Cambodia (Kingdom of)',515);
INSERT INTO define_ais_dac (country,code) VALUES ('Cameroon (Republic of)',613);
INSERT INTO define_ais_dac (country,code) VALUES ('Canada',316);
INSERT INTO define_ais_dac (country,code) VALUES ('Cape Verde (Republic of)',617);
INSERT INTO define_ais_dac (country,code) VALUES ('Cayman Islands',319);
INSERT INTO define_ais_dac (country,code) VALUES ('Central African Republic',612);
INSERT INTO define_ais_dac (country,code) VALUES ('Chad (Republic of)',670);
INSERT INTO define_ais_dac (country,code) VALUES ('Chile',725);
INSERT INTO define_ais_dac (country,code) VALUES ('China (People''s Republic of)',413);
INSERT INTO define_ais_dac (country,code) VALUES ('China (People''s Republic of)',413);
INSERT INTO define_ais_dac (country,code) VALUES ('Christmas Island (Indian Ocean)',516);
INSERT INTO define_ais_dac (country,code) VALUES ('Cocos (Keeling) Islands',523);
INSERT INTO define_ais_dac (country,code) VALUES ('Colombia (Republic of)',730);
INSERT INTO define_ais_dac (country,code) VALUES ('Comoros (Union of the)',616);
INSERT INTO define_ais_dac (country,code) VALUES ('Congo (Republic of the)',615);
INSERT INTO define_ais_dac (country,code) VALUES ('Cook Islands',518);
INSERT INTO define_ais_dac (country,code) VALUES ('Costa Rica',321);
INSERT INTO define_ais_dac (country,code) VALUES ('Côte d''Ivoire (Republic of)',619);
INSERT INTO define_ais_dac (country,code) VALUES ('Croatia (Republic of)',238);
INSERT INTO define_ais_dac (country,code) VALUES ('Crozet Archipelago',618);
INSERT INTO define_ais_dac (country,code) VALUES ('Cuba',323);
INSERT INTO define_ais_dac (country,code) VALUES ('Cyprus (Republic of)',209);
INSERT INTO define_ais_dac (country,code) VALUES ('Cyprus (Republic of)',210);
INSERT INTO define_ais_dac (country,code) VALUES ('Cyprus (Republic of)',212);
INSERT INTO define_ais_dac (country,code) VALUES ('Czech Republic',270);
INSERT INTO define_ais_dac (country,code) VALUES ('Democratic People''s Republic of Korea',445);
INSERT INTO define_ais_dac (country,code) VALUES ('Democratic Republic of the Congo',676);
INSERT INTO define_ais_dac (country,code) VALUES ('Denmark',219);
INSERT INTO define_ais_dac (country,code) VALUES ('Denmark',220);
INSERT INTO define_ais_dac (country,code) VALUES ('Djibouti (Republic of)',621);
INSERT INTO define_ais_dac (country,code) VALUES ('Dominica (Commonwealth of)',325);
INSERT INTO define_ais_dac (country,code) VALUES ('Dominican Republic',327);
INSERT INTO define_ais_dac (country,code) VALUES ('Ecuador',735);
INSERT INTO define_ais_dac (country,code) VALUES ('Egypt (Arab Republic of)',622);
INSERT INTO define_ais_dac (country,code) VALUES ('El Salvador (Republic of)',359);
INSERT INTO define_ais_dac (country,code) VALUES ('Equatorial Guinea (Republic of)',631);
INSERT INTO define_ais_dac (country,code) VALUES ('Eritrea',625);
INSERT INTO define_ais_dac (country,code) VALUES ('Estonia (Republic of)',276);
INSERT INTO define_ais_dac (country,code) VALUES ('Ethiopia (Federal Democratic Republic of)',624);
INSERT INTO define_ais_dac (country,code) VALUES ('Falkland Islands (Malvinas)',740);
INSERT INTO define_ais_dac (country,code) VALUES ('Faroe Islands',231);
INSERT INTO define_ais_dac (country,code) VALUES ('Fiji (Republic of)',520);
INSERT INTO define_ais_dac (country,code) VALUES ('Finland',230);
INSERT INTO define_ais_dac (country,code) VALUES ('France',226);
INSERT INTO define_ais_dac (country,code) VALUES ('France',227);
INSERT INTO define_ais_dac (country,code) VALUES ('France',228);
INSERT INTO define_ais_dac (country,code) VALUES ('French Polynesia',546);
INSERT INTO define_ais_dac (country,code) VALUES ('Gabonese Republic',626);
INSERT INTO define_ais_dac (country,code) VALUES ('Gambia (Republic of the)',629);
INSERT INTO define_ais_dac (country,code) VALUES ('Georgia',213);
INSERT INTO define_ais_dac (country,code) VALUES ('Germany (Federal Republic of)',211);
INSERT INTO define_ais_dac (country,code) VALUES ('Germany (Federal Republic of)',218);
INSERT INTO define_ais_dac (country,code) VALUES ('Ghana',627);
INSERT INTO define_ais_dac (country,code) VALUES ('Gibraltar',236);
INSERT INTO define_ais_dac (country,code) VALUES ('Greece',237);
INSERT INTO define_ais_dac (country,code) VALUES ('Greece',239);
INSERT INTO define_ais_dac (country,code) VALUES ('Greece',240);
INSERT INTO define_ais_dac (country,code) VALUES ('Greenland',331);
INSERT INTO define_ais_dac (country,code) VALUES ('Grenada',330);
INSERT INTO define_ais_dac (country,code) VALUES ('Guadeloupe (French Department of)',329);
INSERT INTO define_ais_dac (country,code) VALUES ('Guatemala (Republic of)',332);
INSERT INTO define_ais_dac (country,code) VALUES ('Guiana (French Department of)',745);
INSERT INTO define_ais_dac (country,code) VALUES ('Guinea (Republic of)',632);
INSERT INTO define_ais_dac (country,code) VALUES ('Guinea-Bissau (Republic of)',630);
INSERT INTO define_ais_dac (country,code) VALUES ('Guyana',750);
INSERT INTO define_ais_dac (country,code) VALUES ('Haiti (Republic of)',336);
INSERT INTO define_ais_dac (country,code) VALUES ('Honduras (Republic of)',334);
INSERT INTO define_ais_dac (country,code) VALUES ('Hong Kong (Special Administrative Region of China)',477);
INSERT INTO define_ais_dac (country,code) VALUES ('Hungary (Republic of)',243);
INSERT INTO define_ais_dac (country,code) VALUES ('Iceland',251);
INSERT INTO define_ais_dac (country,code) VALUES ('India (Republic of)',419);
INSERT INTO define_ais_dac (country,code) VALUES ('Indonesia (Republic of)',525);
INSERT INTO define_ais_dac (country,code) VALUES ('Iran (Islamic Republic of)',422);
INSERT INTO define_ais_dac (country,code) VALUES ('Iraq (Republic of)',425);
INSERT INTO define_ais_dac (country,code) VALUES ('Ireland',250);
INSERT INTO define_ais_dac (country,code) VALUES ('Israel (State of)',428);
INSERT INTO define_ais_dac (country,code) VALUES ('Italy',247);
INSERT INTO define_ais_dac (country,code) VALUES ('Jamaica',339);
INSERT INTO define_ais_dac (country,code) VALUES ('Japan',431);
INSERT INTO define_ais_dac (country,code) VALUES ('Japan',432);
INSERT INTO define_ais_dac (country,code) VALUES ('Jordan (Hashemite Kingdom of)',438);
INSERT INTO define_ais_dac (country,code) VALUES ('Kazakhstan (Republic of)',436);
INSERT INTO define_ais_dac (country,code) VALUES ('Kenya (Republic of)',634);
INSERT INTO define_ais_dac (country,code) VALUES ('Kerguelen Islands',635);
INSERT INTO define_ais_dac (country,code) VALUES ('Kiribati (Republic of)',529);
INSERT INTO define_ais_dac (country,code) VALUES ('Korea (Republic of)',440);
INSERT INTO define_ais_dac (country,code) VALUES ('Korea (Republic of)',441);
INSERT INTO define_ais_dac (country,code) VALUES ('Kuwait (State of)',447);
INSERT INTO define_ais_dac (country,code) VALUES ('Lao People''s Democratic Republic',531);
INSERT INTO define_ais_dac (country,code) VALUES ('Latvia (Republic of)',275);
INSERT INTO define_ais_dac (country,code) VALUES ('Lebanon',450);
INSERT INTO define_ais_dac (country,code) VALUES ('Lesotho (Kingdom of)',644);
INSERT INTO define_ais_dac (country,code) VALUES ('Liberia (Republic of)',636);
INSERT INTO define_ais_dac (country,code) VALUES ('Liberia (Republic of)',637);
INSERT INTO define_ais_dac (country,code) VALUES ('Liechtenstein (Principality of)',252);
INSERT INTO define_ais_dac (country,code) VALUES ('Lithuania (Republic of)',277);
INSERT INTO define_ais_dac (country,code) VALUES ('Luxembourg',253);
INSERT INTO define_ais_dac (country,code) VALUES ('Macedonia (Republic of)',274);
INSERT INTO define_ais_dac (country,code) VALUES ('Madagascar (Republic of)',647);
INSERT INTO define_ais_dac (country,code) VALUES ('Madeira (Portuguese isles of)',255);
INSERT INTO define_ais_dac (country,code) VALUES ('Malawi',655);
INSERT INTO define_ais_dac (country,code) VALUES ('Malaysia',533);
INSERT INTO define_ais_dac (country,code) VALUES ('Maldives (Republic of)',455);
INSERT INTO define_ais_dac (country,code) VALUES ('Mali (Republic of)',649);
INSERT INTO define_ais_dac (country,code) VALUES ('Malta',215);
INSERT INTO define_ais_dac (country,code) VALUES ('Malta',248);
INSERT INTO define_ais_dac (country,code) VALUES ('Malta',249);
INSERT INTO define_ais_dac (country,code) VALUES ('Malta',256);
INSERT INTO define_ais_dac (country,code) VALUES ('Marshall Islands (Republic of the)',538);
INSERT INTO define_ais_dac (country,code) VALUES ('Martinique (French Department of)',347);
INSERT INTO define_ais_dac (country,code) VALUES ('Mauritania (Islamic Republic of)',654);
INSERT INTO define_ais_dac (country,code) VALUES ('Mauritius (Republic of)',645);
INSERT INTO define_ais_dac (country,code) VALUES ('Mexico',345);
INSERT INTO define_ais_dac (country,code) VALUES ('Micronesia (Federated States of)',510);
INSERT INTO define_ais_dac (country,code) VALUES ('Moldova (Republic of)',214);
INSERT INTO define_ais_dac (country,code) VALUES ('Monaco (Principality of)',254);
INSERT INTO define_ais_dac (country,code) VALUES ('Mongolia',457);
INSERT INTO define_ais_dac (country,code) VALUES ('Montenegro (Republic of)',262);
INSERT INTO define_ais_dac (country,code) VALUES ('Montserrat',348);
INSERT INTO define_ais_dac (country,code) VALUES ('Morocco (Kingdom of)',242);
INSERT INTO define_ais_dac (country,code) VALUES ('Mozambique (Republic of)',650);
INSERT INTO define_ais_dac (country,code) VALUES ('Myanmar (Union of)',506);
INSERT INTO define_ais_dac (country,code) VALUES ('Namibia (Republic of)',659);
INSERT INTO define_ais_dac (country,code) VALUES ('Nauru (Republic of)',544);
INSERT INTO define_ais_dac (country,code) VALUES ('Nepal',459);
INSERT INTO define_ais_dac (country,code) VALUES ('Netherlands (Kingdom of the)',244);
INSERT INTO define_ais_dac (country,code) VALUES ('Netherlands (Kingdom of the)',245);
INSERT INTO define_ais_dac (country,code) VALUES ('Netherlands (Kingdom of the)',246);
INSERT INTO define_ais_dac (country,code) VALUES ('Netherlands Antilles',306);
INSERT INTO define_ais_dac (country,code) VALUES ('New Caledonia',540);
INSERT INTO define_ais_dac (country,code) VALUES ('New Zealand',512);
INSERT INTO define_ais_dac (country,code) VALUES ('Nicaragua',350);
INSERT INTO define_ais_dac (country,code) VALUES ('Niger (Republic of the)',656);
INSERT INTO define_ais_dac (country,code) VALUES ('Nigeria (Federal Republic of)',657);
INSERT INTO define_ais_dac (country,code) VALUES ('Niue',542);
INSERT INTO define_ais_dac (country,code) VALUES ('Northern Mariana Islands (Commonwealth of the)',536);
INSERT INTO define_ais_dac (country,code) VALUES ('Norway',257);
INSERT INTO define_ais_dac (country,code) VALUES ('Norway',258);
INSERT INTO define_ais_dac (country,code) VALUES ('Norway',259);
INSERT INTO define_ais_dac (country,code) VALUES ('Oman (Sultanate of)',461);
INSERT INTO define_ais_dac (country,code) VALUES ('Pakistan (Islamic Republic of)',463);
INSERT INTO define_ais_dac (country,code) VALUES ('Palau (Republic of)',511);
INSERT INTO define_ais_dac (country,code) VALUES ('Palestinian Authority (based on Resolution 99 of PP-98)',443);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',351);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',352);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',353);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',354);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',355);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',356);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',357);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',371);
INSERT INTO define_ais_dac (country,code) VALUES ('Panama (Republic of)',372);
INSERT INTO define_ais_dac (country,code) VALUES ('Papua New Guinea',553);
INSERT INTO define_ais_dac (country,code) VALUES ('Paraguay (Republic of)',755);
INSERT INTO define_ais_dac (country,code) VALUES ('Peru',760);
INSERT INTO define_ais_dac (country,code) VALUES ('Philippines (Republic of the)',548);
INSERT INTO define_ais_dac (country,code) VALUES ('Pitcairn Island',555);
INSERT INTO define_ais_dac (country,code) VALUES ('Poland (Republic of)',261);
INSERT INTO define_ais_dac (country,code) VALUES ('Portugal',263);
INSERT INTO define_ais_dac (country,code) VALUES ('Puerto Rico',358);
INSERT INTO define_ais_dac (country,code) VALUES ('Qatar (State of)',466);
INSERT INTO define_ais_dac (country,code) VALUES ('Réunion (French Department of)',660);
INSERT INTO define_ais_dac (country,code) VALUES ('Romania',264);
INSERT INTO define_ais_dac (country,code) VALUES ('Russian Federation',273);
INSERT INTO define_ais_dac (country,code) VALUES ('Rwandese Republic',661);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Helena',665);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Kitts and Nevis',341);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Lucia',343);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Paul and Amsterdam Islands',607);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Pierre and Miquelon (Territorial Collectivity of)',361);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Vincent and the Grenadines',375);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Vincent and the Grenadines',376);
INSERT INTO define_ais_dac (country,code) VALUES ('Saint Vincent and the Grenadines',377);
INSERT INTO define_ais_dac (country,code) VALUES ('Samoa (Independent State of)',561);
INSERT INTO define_ais_dac (country,code) VALUES ('San Marino (Republic of)',268);
INSERT INTO define_ais_dac (country,code) VALUES ('São Tomé and Príncipe (Democratic Republic of)',668);
INSERT INTO define_ais_dac (country,code) VALUES ('Saudi Arabia (Kingdom of)',403);
INSERT INTO define_ais_dac (country,code) VALUES ('Senegal (Republic of)',663);
INSERT INTO define_ais_dac (country,code) VALUES ('Serbia',279);
INSERT INTO define_ais_dac (country,code) VALUES ('Seychelles (Republic of)',664);
INSERT INTO define_ais_dac (country,code) VALUES ('Sierra Leone',667);
INSERT INTO define_ais_dac (country,code) VALUES ('Singapore (Republic of)',563);
INSERT INTO define_ais_dac (country,code) VALUES ('Singapore (Republic of)',564);
INSERT INTO define_ais_dac (country,code) VALUES ('Slovakia',267);
INSERT INTO define_ais_dac (country,code) VALUES ('Slovenia (Republic of)',278);
INSERT INTO define_ais_dac (country,code) VALUES ('Socialist People''s Libyan Arab Jamahiriya',642);
INSERT INTO define_ais_dac (country,code) VALUES ('Solomon Islands',557);
INSERT INTO define_ais_dac (country,code) VALUES ('Somali Democratic Republic',666);
INSERT INTO define_ais_dac (country,code) VALUES ('South Africa (Republic of)',601);
INSERT INTO define_ais_dac (country,code) VALUES ('Spain',224);
INSERT INTO define_ais_dac (country,code) VALUES ('Spain',225);
INSERT INTO define_ais_dac (country,code) VALUES ('Sri Lanka (Democratic Socialist Republic of)',417);
INSERT INTO define_ais_dac (country,code) VALUES ('Sudan (Republic of the)',662);
INSERT INTO define_ais_dac (country,code) VALUES ('Suriname (Republic of)',765);
INSERT INTO define_ais_dac (country,code) VALUES ('Swaziland (Kingdom of)',669);
INSERT INTO define_ais_dac (country,code) VALUES ('Sweden',265);
INSERT INTO define_ais_dac (country,code) VALUES ('Sweden',266);
INSERT INTO define_ais_dac (country,code) VALUES ('Switzerland (Confederation of)',269);
INSERT INTO define_ais_dac (country,code) VALUES ('Syrian Arab Republic',468);
INSERT INTO define_ais_dac (country,code) VALUES ('Taiwan (Republic of China)',416);
INSERT INTO define_ais_dac (country,code) VALUES ('Tanzania (United Republic of)',674);
INSERT INTO define_ais_dac (country,code) VALUES ('Tanzania (United Republic of)',677);
INSERT INTO define_ais_dac (country,code) VALUES ('Thailand',567);
INSERT INTO define_ais_dac (country,code) VALUES ('Togolese Republic',671);
INSERT INTO define_ais_dac (country,code) VALUES ('Tonga (Kingdom of)',570);
INSERT INTO define_ais_dac (country,code) VALUES ('Trinidad and Tobago',362);
INSERT INTO define_ais_dac (country,code) VALUES ('Tunisia',672);
INSERT INTO define_ais_dac (country,code) VALUES ('Turkey',271);
INSERT INTO define_ais_dac (country,code) VALUES ('Turkmenistan',434);
INSERT INTO define_ais_dac (country,code) VALUES ('Turks and Caicos Islands',364);
INSERT INTO define_ais_dac (country,code) VALUES ('Tuvalu',572);
INSERT INTO define_ais_dac (country,code) VALUES ('Uganda (Republic of)',675);
INSERT INTO define_ais_dac (country,code) VALUES ('Ukraine',272);
INSERT INTO define_ais_dac (country,code) VALUES ('United Arab Emirates',470);
INSERT INTO define_ais_dac (country,code) VALUES ('United Kingdom of Great Britain and Northern Ireland',232);
INSERT INTO define_ais_dac (country,code) VALUES ('United Kingdom of Great Britain and Northern Ireland',233);
INSERT INTO define_ais_dac (country,code) VALUES ('United Kingdom of Great Britain and Northern Ireland',234);
INSERT INTO define_ais_dac (country,code) VALUES ('United Kingdom of Great Britain and Northern Ireland',235);
INSERT INTO define_ais_dac (country,code) VALUES ('United States Virgin Islands',379);
INSERT INTO define_ais_dac (country,code) VALUES ('United States of America',338);
INSERT INTO define_ais_dac (country,code) VALUES ('United States of America',366);
INSERT INTO define_ais_dac (country,code) VALUES ('United States of America',367);
INSERT INTO define_ais_dac (country,code) VALUES ('United States of America',368);
INSERT INTO define_ais_dac (country,code) VALUES ('United States of America',369);
INSERT INTO define_ais_dac (country,code) VALUES ('Uruguay (Eastern Republic of)',770);
INSERT INTO define_ais_dac (country,code) VALUES ('Vanuatu (Republic of)',576);
INSERT INTO define_ais_dac (country,code) VALUES ('Vatican City State',208);
INSERT INTO define_ais_dac (country,code) VALUES ('Venezuela (Bolivarian Republic of)',775);
INSERT INTO define_ais_dac (country,code) VALUES ('Vietnam (Socialist Republic of)',574);
INSERT INTO define_ais_dac (country,code) VALUES ('Wallis and Futuna Islands',578);
INSERT INTO define_ais_dac (country,code) VALUES ('Yemen (Republic of)',473);
INSERT INTO define_ais_dac (country,code) VALUES ('Yemen (Republic of)',475);
INSERT INTO define_ais_dac (country,code) VALUES ('Zambia (Republic of)',678);
INSERT INTO define_ais_dac (country,code) VALUES ('Zimbabwe (Republic of)',679);
