#!/usr/bin/env python
'''Filter xy xxx data position data.'''

__version__ = '$Revision: 8449 $'.split()[1]
__date__ = '$Date: 2008-01-31 11:11:50 -0500 (Thu, 31 Jan 2008) $'.split()[1]
__author__ = 'Kurt Schwehr'


if __name__=='__main__':
    from optparse import OptionParser
    parser = OptionParser(usage="%prog [options] file1.xy [file2.xy ...]",version="%prog "+__version__)
    parser.add_option('-e','--epsilon'
                      ,dest='epsilon'
                      ,default=0.001
                      ,type='float'
                      ,help='Distance between adjacent points to consider them different[default: %default]')
    (options,args) = parser.parse_args()
    epsilon = options.epsilon

    for filename in args:
        last = None
        for line in file(filename):
            x,y=line.split()[:2]
            x=float(x)
            y=float(y)
            if last==None:
                last=(x,y)
                print line,
                continue
            if (x<last[0]-epsilon or x>last[0]+epsilon) and (y<last[1]-epsilon or y>last[1]+epsilon):
                last=(x,y)
                print line,
